
GET http://localhost:5052/games

###

GET http://localhost:5052/games/4

###

POST http://localhost:5052/games
Content-Type: application/json

{
  "name": "Game 2222",
  "genre": "RP11G",
  "price": 59.99,
  "releaseDate": "2025-01-01"
}

###
PUT http://localhost:5052/games/1
Content-Type: application/json

{
  "name": "Updated Game 1",
  "genre": "Action",
  "price": 4009.99,
  "releaseDate": "2023-01-01"
}

###
DELETE http://localhost:5052/games/1